project: 
  type: website

website: 
  page-navigation: true
  title: "ftnirs-ml-application Home" 
  site-url: "https://noaa-afsc.github.io/ftnirs-ml-application/" 
  repo-url: "https://github.com/noaa-afsc/ftnirs-ml-application"
  repo-actions: [edit, source, issue]
  favicon: images/fishy2.jpg
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/79/NOAA_logo.svg"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: app
        href: https://github.com/DanWoodrichNOAA/ftnirs-mlapp
        text: "application repository"
      - icon: cpu
        href: https://github.com/DanWoodrichNOAA/ftnirs-ml-codebase
        text: "codebase repository"
      - icon: globe
        href: https://github.com/noaa-afsc/ftnirs-ml-application
        text: "Site repository"


    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: content/Background.qmd
        text: "Background"
        contents:
          - href: content/backScience.qmd
            text: "The science"
          - href: content/backDesign.qmd
            text: "The design"
      - href: content/Use.qmd
        text: "Use"
        contents:
          - href: content/useApp.qmd
            text: "The app"
          - href: content/useCodebase.qmd
            text: "The codebase"
      - href: content/Examples.qmd
        text: "Examples"
        contents:
          - href: content/dataPrep.qmd
            text: "Data preparation"
          - href: content/exApp.qmd
            text: "The app"
          - href: content/exCodebase.qmd
            text: "The codebase"
          - href: content/Integrative.qmd
            text: "Integrative"
      - href: content/Contributing.qmd
        text: "Contributing"
        contents:
          - href: content/contScience.qmd
            text: "Evolving scientific techniques"
          - href: content/contApp.qmd
            text: "App features"
          - href: content/contDocumentation.qmd
            text: "The documentation"
      - href: content/Maintaining.qmd
        text: "Maintaining"
        contents:
          - href: content/maintApp.qmd
            text: "App data and models"
          - href: content/selfHost.qmd
            text: "Self-hosting"
      - href: content/futDirections.qmd
        text: "Future Directions"
      - href: content/FAQ.qmd
        text: "FAQ"
        
format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
