---
title: Future Directions
---

Application engineer perspective: 

The application works well to prove that the scientific concept can be delivered in a graphical way with limited development time and no specialized front end experience- no small feat!

The application lacks certain concepts that will may make using in production difficult and/or scaling up to an enterprise service: 
1. No user identity associated, so application datasets and models cannot be managed in the application
2. Datasets are flexibile w.r.t columns, but to experiment with different subsets along rows, datasets need to be manually filtered and reuploaded. This creates more steps, leads to clutter in the application datasets, and increases the maintainance burden
3. The application is NOAA internal as the use of models is highly computationally resource consumptive, and allows for non-public data to be kept private. This leads to certain difficulties, like coordination with the network team to scale out the service, internal processes for DNS (domain name and certificate). However, maybe a public facing site in the future is more ideal if NMFS can afford to provide the computational resources. 
4. The website is built using python Dash, which isn't a standard in most development team's skillset, and has plently of limitations as a framework. Refactoring the front end into a javascript framework would allow for an enterprise dev team to own the product for continued support. 

Addressing these concepts during future engineering work will help the application scale to more users. 

Lab/scientific staff perspective: 

?

